# Serverless Framework config

service: lunchbot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  environment:
    DYNAMODB_TABLE_INDEX_BY_MONTH: by_month
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    LOG_LEVEL: ${self:custom.environment.LOG_LEVEL}
    SLACK_API_TOKEN: ${self:custom.environment.SLACK_API_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:BatchWriteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
  stackTags:
    project: lunchbot
  tags:
    project: lunchbot

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

functions:
  on_slack_event:
    handler: lunchbot.handlers.on_slack_event
    events:
      - http:
          path: events
          method: post
          cors: true
  generate_monthly_report:
    handler: lunchbot.handlers.generate_monthly_report
    events:
      - schedule:
          rate: cron(0 16 ? * 6L *)
          input:
            dry_run: false
  record_months:
    handler: lunchbot.handlers.record_months

resources:
  Resources:
    LunchbotDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: timestamp
            AttributeType: N
          -
            AttributeName: user_id
            AttributeType: S
          -
            AttributeName: month
            AttributeType: S
        KeySchema:
          -
            AttributeName: user_id
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        GlobalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.DYNAMODB_TABLE_INDEX_BY_MONTH}
            KeySchema:
              -
                AttributeName: month
                KeyType: HASH
              -
                AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

custom:
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN_NAME, "false"}
    enabled: ${self:custom.environment.CUSTOM_DOMAIN_ENABLED, "false"}
    certificateName: ${self:custom.environment.CUSTOM_DOMAIN_CERTIFICATE_NAME, "false"}
    createRoute53Record: ${self:custom.environment.CREATE_ROUTE_53_RECORD_FOR_CUSTOM_DOMAIN, "false"}
